CREATE TABLE "user" (
    "id" SERIAL PRIMARY KEY,
    "username" VARCHAR (80) UNIQUE NOT NULL,
    "password" VARCHAR (1000) NOT NULL,
    "proficiency_level" DECIMAL DEFAULT 1.00,
    "favorite_trick" VARCHAR (200),
    "favorite_kendama" VARCHAR (200) 
);

CREATE TABLE "trick" (
    "id" SERIAL PRIMARY KEY,
    "name" VARCHAR (200) NOT NULL,
    "level" INT NOT NULL,
    "description" VARCHAR (800),
    "video_url" VARCHAR (2000)
);

CREATE TABLE "user_trick" (
    "id" SERIAL PRIMARY KEY,
    "user_id" INT REFERENCES "user",
    "trick_id" INT REFERENCES "trick",
    "session_countdown" INT NOT NULL DEFAULT 0,
    "mastery_level" INT NOT NULL DEFAULT 0,
    "hidden" BOOLEAN NOT NULL DEFAULT FALSE,
    "note" VARCHAR (1000)
);

INSERT INTO "trick" ("name", "level", "description", "video_url")
VALUES ('Airplane', 1, 'In tama grip, swing the kendama into the tama hole', 'https://youtu.be/RU_BgssM4Eo?si=iCQO9XWfqTAnodPx&t=5'),
('Swing Spike', 1, 'Swing the tama onto the spike.', 'https://youtu.be/RU_BgssM4Eo?si=0CMUqt0N67X-1rsm&t=12'),
('Around Japan', 1, 'Big cup, little cup, in' , 'https://youtu.be/RU_BgssM4Eo?si=K91Kn0MJu2xfPCkK&t=17'),
('Around the World', 1, 'Big cup, little cup, base cup, in', 'https://youtu.be/RU_BgssM4Eo?si=DFDQD6x58rOj3bW2&t=26'),
('Trapeze', 1, 'Starting with tama spiked and kendama hanging, pinch and hold the string, swing the entire kendama toward oneself, grab the ken with base cup facing up, land the tama on base cup', 'https://youtu.be/RU_BgssM4Eo?si=A6HoLO0uBpH0fFQ4&t=34'),
('Baseball, Cup', 1, 'In Sara grip, big cup, knock tama off counter clockwise with base cup, land in base cup', 'https://youtu.be/RU_BgssM4Eo?si=qk4HB8S8ugJlOiVo&t=42'),
('Big Cup, Knee Bounce, Big Cup', 1, 'Do not need to in', 'https://youtu.be/RU_BgssM4Eo?si=iA4RiPLzDlSRFvyT&t=52'),
('Big Cup, Orbit, Spike', 1, 'For the Orbit, toss the tama into the area, swing the kendama around the tama, and then land it back into Big Cup', 'https://youtu.be/RU_BgssM4Eo?si=GuMDvWjj9SiWuT-f&t=56'),
('Flying Top', 1, 'Starting with tama spiked, spin the tama and toss it into the area, catch tama back on spike', 'https://youtu.be/RU_BgssM4Eo?si=xD5TRVcV4JuLSGDu&t=66'),
('Moshikame x11', 1, 'In Sara grip, land in big cup first, go back and forth from big cup and base cup a total of 11 times, do not need to spike in', 'https://youtu.be/RU_BgssM4Eo?si=tVsklxKNihxWZkW1&t=72'),
('Spike', 1, 'Pull the hanging tama up onto the spike', 'https://youtu.be/irHY24_wDO4?si=hFziu31IeGllFQ5k&t=5'),
('Penguin Base Cup', 1, 'Land base cup in Penguin grip, a grip where the wrist is turned down and the basecup is facing up', 'https://youtu.be/irHY24_wDO4?si=aCBa9i1UCf1k7v6r&t=46'),
('Scooping Goldfish', 1, 'With the tama on the ground and hole facing downwards, scoop the tama onto the Big Cup', 'https://youtu.be/irHY24_wDO4?si=8wuy_GgVAbaYYn9b&t=53'),
('Big Cup, Arm Bounce, Big Cup', 1, 'Bounce off the inside forearm and land back in Big Cup','https://youtu.be/jYYTFzdN95o?si=-6GCdOqLfJsoELY9&t=18'),
('Tama Grip, Throw to Big Cup', 1, 'Swing and throw tama clockwise, grab ken and land tama in Big Cup', 'https://youtu.be/JUw4rqIe5hM?si=M3JZfTcrVMWX48Se&t=56'),
('Frying Pan, Spike', 1, 'Frying Pan position is where the sarado and sword meet', 'https://youtu.be/JUw4rqIe5hM?si=kdhuQIpgwsZ7MVS3&t=63'),
('Candle Block', 1, 'Candle Stick grip (holding the spike between fingers), Big Cup, Little Cup, Base Cup, do not need to spike in', 'https://youtu.be/Wfy_BV8nnQY?si=UDey4m0-gCR_4JWA&t=86'),
('Big Cup, Spike', 1, 'Land the tama on the big cup, then spike the tama', 'https://youtu.be/996Iysfiee4?si=dbYVcXqhuhIRP6tW&t=21'),
('Hanging Clap Catch', 1, 'Starting with tama spiked and kendama hanging, pinch and hold the string, toss the entire kendama in the air, clap hands together once and catch kendama', 'https://youtu.be/UGfWR_DlXM8?si=kXGSunFc6BKiYpWD&t=77'),
('Base Cup', 1, 'Land the tama in the base cup', 'https://youtu.be/UGfWR_DlXM8?si=d7UcEa85n-7uxe6z&t=5'),
('Easy Big Cup', 1, 'Manually place the tama onto the Big Cup, then spike the tama', 'https://youtu.be/UGfWR_DlXM8?si=wzPbMvlZsDqc0J0r&t=24'),
('Candlestick', 1, 'Candle Stick grip (holding the spike between fingers), land in Big Cup', 'https://youtu.be/tNFPXYIIhyo?si=U9FPbiDArtH8b8mu&t=61'),
('Big Cup', 1 , 'Land the tama on the big cup', 'https://youtu.be/6dgR6BhcOU0?si=ojzikBhNwMy70GKa&t=83'),
('1-Turn Airplane', 2, 'In tama grip, pull the ken so that it turns one time before spiking it', 'https://youtu.be/JkT9GhOB8ZE?si=oLpINhA3z5hZ92os&t=6'),
('Swing Spike, Earth Turn', 2, 'Earth Turn is flipping the tama one time when it is spiked', 'https://youtu.be/JkT9GhOB8ZE?si=gnWsAmZPwzv7Bbng&t=13'),
('Scrambled Airplane', 2, 'Swing the Ken like a normal Airplane, as the Ken comes around, release and flip the tama in your hand, let the Ken swing around one more time and spike into the Tama , on ', 'https://youtu.be/JkT9GhOB8ZE?si=BZJUC-M2XdwI5ozK&t=17'),
('Jumping Stick', 2, 'Jumping stick is flipping the ken one time when it is spiked', 'https://youtu.be/JkT9GhOB8ZE?si=pOppz9llGp6BcUn1&t=23'),
('Bird, Spike', 2, 'Bird is landing the the Tama onto the top edge of the Big Cup', 'https://youtu.be/JkT9GhOB8ZE?si=Yo4TH_h-SsgMwMrz&t=31'),
('Tap In', 2 , 'In Tama grip, pull the kendama up, tap the Base Cup to make the Ken do half a rotation and in', 'https://youtu.be/JkT9GhOB8ZE?si=Iy4AG7uZnhARq-6l&t=39'),
('Stuntplane', 2, 'In Tama grip, pull the kendama up and Spike the Ken with the Tama in a downwards motion', 'https://youtu.be/JkT9GhOB8ZE?si=bG5OKV9g5KnbHpDL&t=42'),
('Hanging Spike', 2, 'Pinch the string so the tama is hanging evenly with the sarado, pull up both the tama and ken and grab the ken and spike the tama' ,'https://youtu.be/JkT9GhOB8ZE?si=75-8TEy2Z6yr-17e&t=51'),
('Lighthouse, Falling In', 2, 'In Tama grip, pull the ken up so the Base Cup lands on top of the Tama, toss the Ken up so that the spike falls into the tama', 'https://youtu.be/JkT9GhOB8ZE?si=zOtUQVofksEjI1e9&t=61'),
('Downspike', 2, 'In Sara grip, pull the tama up and then spike the tama in a downwards motion', 'https://youtu.be/JkT9GhOB8ZE?si=jGPNDBK7nrTCNoJg&t=72'),
('Around Europe', 2, 'Big Cup, Spike, Little Cup, Spike, Base Cup, Spike', 'https://youtu.be/SZvJYUGDInE?si=-46fut62hQ3KLH6-&t=17'),
('Tama Grip, Throw to Big Cup, Spike', 2, 'Throw the Tama in the air and switch to Sara grip and land the Tama in Big Cup.', 'https://youtu.be/SZvJYUGDInE?si=rTHUwbU2TTtORJfy&t=26'),
('Ken Flip Big Cup, Spike', 2, 'Pull the Tama up and also flip the Ken one rotation, catching the Ken and then catching the Tama in Big Cup. Spike.', 'https://youtu.be/SZvJYUGDInE?si=UQLagWI2GBzgw6Qz&t=32'),
('Airplane, Base Cup, Downspike', 2, 'After Airplane, toss the Kendama up and grab the Ken out and land the Tama in Base Cup. Then toss the Tama up to spike it in a downwards motion.', 'https://youtu.be/SZvJYUGDInE?si=OYeQdbutdqdxLPT-&t=61'),
('Turntable, Spike', 2, 'Big Cup, spin the Ken one entire rotation and catch the handle again', 'https://youtu.be/MWaKo5w5fFc?si=2krDlbIbF_rQ9RC2&t=35'),
('Bird, 1-Turn Spike', 2, 'Pull the Tama up and land the Tama bevel on the top edge of the Big Cup', 'https://youtu.be/MWaKo5w5fFc?si=r4UEORs6BKbvHjsw&t=48'),
('Flying V, Airplane', 2, 'Holding the Ken, swing the Tama around and let the string wrap around your index finger and the inner part of the big cup, as the tama comes around, switch the tama your primary hand. You will end up holding the tama in your primary hand, and the string wrapped once around your finger and the edge of the big cup', 'https://youtu.be/MWaKo5w5fFc?si=dYOWsVBUOmqnB1k8&t=67'),
('Base Cup Hanging Spike', 2, 'Hanging Spike position, but the bottom of the ken is on the tama', 'https://youtu.be/VUu9xrkCo3M?si=9gYSemGW7zwN_vvo&t=42'),
('Underbird, Spike', 2, 'Pull the Tama up and land the Tama bevel on the bottom edge of the Big Cup. The Spike will be facing downwards.', 'https://youtu.be/VUu9xrkCo3M?si=p9nRpFDEe-IVDpKq&t=59'),
('Gunslinger Spike', 2, 'Place finger underneath Little Cup, rotate Ken around finger while also pulling Tama up to Spike it.', 'https://youtu.be/RCAFNUbVylc?si=JiPxuWCWeW74RBg9&t=5'),
('Finger Solar Flare, Spike', 2, 'Solar Flare is having the Tama between finger and spike', 'https://youtu.be/RCAFNUbVylc?si=AUnhb8MQYF8SodT8&t=66'),
('Penguin Base Cup, Spike', 2, 'Land base cup in Penguin grip, a grip where the wrist is turned down and the basecup is facing up. Spike the Tama.', 'https://youtu.be/RCAFNUbVylc?si=1ilIOOktgS6xH84A&t=83'),
('Spike, Flying Top', 2, 'Land a Spike. Then spin the Tama upwards and release it from the Spike, then Spike it again.', 'https://youtu.be/eVS168m-rE8?si=y3kn9wbPFJTmiY7U&t=57'),
('Base Cup, Rising Dragon Spike', 2, 'While holding the ken and tama in base cup, rotate your elbow so the ken is in penguin grip, then continue to rotate so that the ken is back in base cup', 'https://youtu.be/eVS168m-rE8?si=PEr4ubwYQTmToKhJ&t=85'),
('Moshikame x10 or more, Spike', 2, 'In Sara grip, land in big cup first, go back and forth from big cup and base cup a total of 10 times, then Spike.', 'https://youtu.be/9k7dJmRDOao?si=FM-8JbET6KW292Gx&t=11'),
('Spacewalk', 3, 'In Ken grip, swing the Ken and Tama clockwise, releasing both in the air in a circular motion. Catch the Tama and Spike the Ken.', 'https://youtu.be/mYBd6LP2lG8?si=0AYQn01yDfIVIkzB&t=5'),
('Big Cup, Airplane In', 3, 'Land in Big Cup, then toss the Ken up about half a rotation in order to Spike it via Airplane.', 'https://youtu.be/mYBd6LP2lG8?si=G5WRDqnOWFnc3zcn&t=26'),
('Lighthouse, Tap Flip In', 3, 'Tap the Base Cup so that the Ken flips 1.5 rotations total', 'https://youtu.be/mYBd6LP2lG8?si=kDngXwi8Cy1Kqc_Q&t=31'),
('Airplane, Tap Reverse Flip In', 3, 'Flip the Ken out toward oneself, tap the edge of the Base Cup so that the Ken rotates 1.0 back into the tama hole', 'https://youtu.be/mYBd6LP2lG8?si=xZcQr_pwGttG5PuQ&t=43'),
('Big Cup, Ken Flip Big Cup, Spike', 3, 'Land in Base Cup. Toss the Tama up and flip the Ken one rotation, and then grab the Ken and land the Tama on the Big Cup. Spike.', 'https://youtu.be/mYBd6LP2lG8?si=ojk4l66Gr9NslC_L&t=53'),
('Lighthouse, Tradespike', 3, 'Land in Lighthouse, then toss the Tama up in order to switch to Ken grip and Spike the Tama.', 'https://youtu.be/mYBd6LP2lG8?si=a0du_XDbvN9WE18c&t=59'),
('Lighthouse Flip, Falling In', 3, 'Land in Lighthouse. Then flip the Ken so it rotates one time back onto Lighthouse. Then toss the Ken up half a rotation so it lands into Tama hole.', 'https://youtu.be/mYBd6LP2lG8?si=Xl5Bf6cOIkY0nHxX&t=66'),
('Swirl to Airplane (Ken grip Start)', 3, 'Let the string wrap around the finger, release the Ken and let the Ken and Tama spin around the finger at least once, grab the Tama and Airplane In', 'https://youtu.be/zkP89SyaPnI?si=frYURggRKNsaie6y&t=8'),
('Around USA', 3, 'Land each cup, Spike In, and perform an Earth Turn, 9 tricks total', 'https://youtu.be/zkP89SyaPnI?si=z_6I-SCSAUHpM9LR&t=14'),
('Swing Spike, Whirlwind', 3, 'Turn the Tama and Flip the Ken at the same time', 'https://youtu.be/zkP89SyaPnI?si=amHe9pd09shLTzne&t=27'),
('Big Cup, Juggle Big Cup, Spike', 3, 'Land in Big Cup. Then Toss the Tama up, the Ken, the Tama, and grab the Ken in order to land the Tama back into Big Cup. Then Spike.', 'https://youtu.be/zkP89SyaPnI?si=_TTQ9V_NfyxPGi4R&t=32'),
('Nunchuck Airplane', 3, 'Bring the Ken behind your shoulder and so the tama is hanging down, release the ken and catch the tama, then Airplane In', 'https://youtu.be/zkP89SyaPnI?si=C8yiUTd9im841Aw4&t=40'),
('Candle Flip, Spike', 3, 'In Candlestick grip (holding the Spike between fingers), land the Tama on Base Cup. Toss the tama up slightly in order to flip or turn the Ken half a rotation and land in Spike.', 'https://youtu.be/zkP89SyaPnI?si=YElvGfO0ld8Z2JDI&t=53'),
('U.F.O.', 3, 'Airplane. Then turn the Tama so the Ken is sideways and perform a sideways Jumping Stick.', 'https://youtu.be/zkP89SyaPnI?si=E1ejqlyf_pRY6GFy&t=59'),
('Lunar, Flip In', 3, 'In Tama grip, land a Lunar (bottom of Big Cup on Tama). Flip the Ken one rotation and land in Spike.', 'https://youtu.be/zkP89SyaPnI?si=t6XyiIP7vfWTH1Kw&t=64'),
('Juggle Big Cup, Spike', 3, 'In Ken grip, pull the Tama up, then toss the Ken, then toss the Tama, then grab the Ken to land the Tama in Big Cup.', 'https://youtu.be/acmiPn5qhMw?si=4BbISE9Y1_TJREcO&t=42'),
('Lighthouse, Downspike', 3, 'Lighthouse, then toss the Kendama up, grab the Ken and Downspike while the Tama is in the air', 'https://youtu.be/acmiPn5qhMw?si=NujuuOLiXm96lADC&t=47'),
('Cat Jumping Stick', 3, 'Place the spiked Kendama on the top of the hand. In one motion, toss the Ken upwards and grab the Tama. The Ken will rotate once before Spiking it.', 'https://youtu.be/acmiPn5qhMw?si=bI0QHngtuYJ3Opwc&t=67'),
('Downspike, Down Earth', 3, 'Holding the Ken with the Spike downwards, pull up the Tama and Downspike it. After, turn the Tama so that it rotates once and then Downspike it again.', 'https://youtu.be/acmiPn5qhMw?si=cc_1_W_n2sNbHtqw&t=75'),
('Shinma Special', 3, 'Swing Spike. Throw the Tama of the Spike towards oneself, then let the Tama do one full circular rotation at the length of the string before Spiking it again.', 'https://youtu.be/wKfzuUycfzU?si=8qqgf9_6TD51BcS1&t=6'),
('Pinky spike, 1-Turn In', 3, 'Spike the Tama on the pinky finger. Then flip the Tama off so it rotates once and lands on the Spike.', 'https://youtu.be/wKfzuUycfzU?si=P1FdMJS-vu8GWpnJ&t=19'),
('Ghost Lighthouse, Falling In', 3, 'In Ken grip, pull the Tama up, then let go of the Ken and grab the Tama, and land a Lighthouse. Toss the Ken up and perform a half rotation so it lands in the Spike.', 'https://youtu.be/wKfzuUycfzU?si=XqOLNc3sA_u2VDV2&t=44'),
('Base Cup Hanging Lighthouse, Falling In', 3, 'Hanging Base Cup position, toss both Ken and Tama up together and land in Lighthouse. Toss the Ken up and perform a half rotation so it lands in the Spike.', 'https://youtu.be/S1IvAfjD1Hs?si=1s9NeEddIfqBD9dz&t=58'),
('Half Spacewalk', 3, 'In Ken grip, toss the Ken to the outer part of the body, then grab the Tama, then Spike.', 'https://youtu.be/5csssZGE4y0?si=yFWW42QtsbB7wT09&t=16'),
('1-Turn Lighthouse, Tradespike', 3, 'In Tama grip, pull the Ken so it performs a full rotation before landing in Lighthouse position. Then, toss the Ken and Tama up together and switch to Ken grip to spike the Tama while it is in the air.', 'https://youtu.be/5csssZGE4y0?si=CN1XQFsY8FYnLaeG&t=59'),
('Flamingo Spike', 3, 'Lift the leg over the hand holding the Ken and hold this position. While in this position, Spike.', 'https://youtu.be/6hMBjdKG1qs?si=pkWEJ2aeTuZmAc8m&t=10'),
('Around the Universe', 3, 'Land in each of these positions and perform an Earth turn afterwards. Frying Pan (position where the Sarado and Sword cross), Little Cup, Big Cup, Base Cup.', 'https://youtu.be/6hMBjdKG1qs?si=guYviK5mPNZuaAbb&t=24'),
('Stilt', 4, 'In Tama grip, pull the Ken up so that the Ken lands with the spike down, and the top edge of the Big Cup now balances on the Tama bevel.', 'https://youtu.be/G46OTL2m8MY?si=4kecSNP7CzfMhmd0&t=6'),
('Slip Stop Special, Spike', 4, 'In Ken grip, land the tama on the small edge or 2nd notch on the handle of the Ken. Spike.', 'https://youtu.be/G46OTL2m8MY?si=1vREUJ_jZ2KYUHjT&t=13'),
('Jumping Spacewalk', 4, 'Perform a Spacewalk, catch the Tama and while still in control of the Tama, swing the Ken in another circular motion, 1-3 times, then Airplane in as the Ken comes around on the last swing.', 'https://youtu.be/G46OTL2m8MY?si=tGF88Xaw-5HnPu0f&t=26'),
('Half Mooncircle', 4, 'In Tama grip, toss the Tama and Ken forward in a circular motion, grab the Ken after half a rotation, then while the tama is still in its circular rotation, Spike.', 'https://youtu.be/G46OTL2m8MY?si=ILfveDkCnaDoEg4d&t=33'),
('Whirlwind Spike', 4, 'In Ken grip with the Tama hanging down, pull the Tama up and also perform a Ken flip at the same time, Spike while the Tama is still in the air.', 'https://youtu.be/G46OTL2m8MY?si=6YYiuymG32pryhLx&t=39'),
('Hanging 1-Turn Airplane', 4, 'In Hanging grip with the Tama next to the Sarado, pull the Ken so it performs a 1-Turn rotation and then grab the Tama to Airplane in as the Ken completes its rotation.', 'https://youtu.be/G46OTL2m8MY?si=8x3lU8I3GDkVcGEd&t=47'),
('Rising Airplane', 4, 'In Ken grip, bring the Ken and Tama behind the back, toss the Tama up, bring the hand in front of the body to catch the Tama and then Airplane', 'https://youtu.be/G46OTL2m8MY?si=ADTYrFkY_w-ICfpn&t=52'),
('Base Cup Scoop Up', 4, 'With the Tama on the ground, scoop the Tama up using the Base Cup. Do not need to in.', 'https://youtu.be/G46OTL2m8MY?si=ZIGAOVn7ffEhNLJw&t=57'),
('Airplane, Double Inward J-Stick', 4, 'An Inward J-Stick is flipping the Ken the opposite direction of a normal J-Stick. Double means two rotations.', 'https://youtu.be/vi9tU-Atj1U?si=XDY1PWtTF7YNm8YI&t=5'),
('Mooncircle', 4, 'In Ken grip, toss the Ken and Tama in a circular motion one entire rotation in the air together and catch the Ken again before Spiking the Tama.', 'https://youtu.be/vi9tU-Atj1U?si=dpOkQreIofe8BQB0&t=21'),
('Stilt, Flip In', 4, 'In Tama grip, pull the Ken up so that the Ken lands with the spike down, and the top edge of the Big Cup now balances on the Tama bevel. The Ken should rotate one entire rotation before being going in.', 'https://youtu.be/vi9tU-Atj1U?si=Rx4INoG9NFopx_NA&t=29'),
('Airplane, Half Flip Spike', 4, 'Flip the Ken out (this is the half rotation), toss the Tama up, grab the Ken and then Spike.','https://youtu.be/vi9tU-Atj1U?si=6sa-oh3uRU8UoJia&t=36'),
('Spacewalk Handroll Spike', 4, 'Spacewalk and catch like normal, but then let the string wrap around the hand and have the Ken and Tama roll and spin around the entire hand at least one rotation, at the end, grab the Ken and Spike.', 'https://youtu.be/vi9tU-Atj1U?si=dIArWFEnr4FWpDtY&t=65'),
('Hanging Downspike', 4, 'In Hanging grip with the Tama next to the Sarado, pull the Ken and Tama up and grab the Ken with the Spike facing down and Downspike the Tama.', 'https://youtu.be/vi9tU-Atj1U?si=qqGJFcDPBI3iFdTd&t=75'),
('1-Turn Lighthouse, Inward Flip Stuntplane', 4, 'Inward flip is the opposite direction of a normal flip. The Stuntplane happens while the Ken is still is in rotation.', 'https://youtu.be/bZIPasoORnw?si=SkSjdlv9v8Eyg-QN&t=5'),
('Super Flamingo Spacewalk', 4, 'Perform a Spacewalk like normal, when catching the Tama the first time, lift the right leg up above the hand, and then toss the Tama in the air and continue the Spacewalk motion while in this position, return the right foot to the ground and grab the Tama like normal, then lift the left leg above the hand, and then toss the Tama in the air and continue the Spacewalk motion while in this position, return the left foot to the ground and finally catch the Tama one more time before performing an Airplane.', 'https://youtu.be/bZIPasoORnw?si=5XNJUSzAkFLD6yqm&t=13'),
('Handle Stall, Spike', 4, 'Handle Stall position is the edge of the Base Cup', 'https://youtu.be/bZIPasoORnw?si=6JSH0tC3uXMhrO_H&t=21'),
('Lighthouse Flip, Tradespike', 4, 'First perform a Lighthouse, then perform a Lighthouse Flip, then toss both the Ken and Tama in the air and grab the Ken to Spike', 'https://youtu.be/bZIPasoORnw?si=i5dfZ6QZAQWCROTL&t=35'),
('Bat, Falling In', 4, 'Holding the Ken so the Spike faces downward, pull up the Tama so it lands on the underside edge of the Big Cup. Toss the Ken half a rotation and grab the Tama to Spike.', 'https://youtu.be/bZIPasoORnw?si=4AKxOWYvkZ0TOskn&t=45'),
('Ken Flip Bird, Spike', 4, 'Flip the Ken and land in Bird. Then Spike.', 'https://youtu.be/bZIPasoORnw?si=ym-FDhNIEqvEEytx&t=52'),
('Spacewalk, Swap Spike', 4, 'Perform a Spacewalk like normal, toss the Tama up and grab the Ken and Spike.', 'https://youtu.be/bZIPasoORnw?si=A9zbe8g-FuGsXtfQ&t=59'),
('Airplane, Whirlpool Spike', 4, 'Whirlpool Spike is the Ken and Tama together and the string rotates around the finger in front of the player. After performing Whirlpool several times, toss the Tama and Ken up, and grab the Ken to Spike.', 'https://youtu.be/bZIPasoORnw?si=k62eH7HT_7vI0pKQ&t=65'),
('Airplane, 1.5-Turn Tradespike', 4, 'The Ken will rotate one and a half times before the Spike.', 'https://youtu.be/zX1BiKn1i84?si=jT3PbA6DMigsT2hA&t=5'),
('Stuntplane, Fasthand Penguin, Penguin Earth Turn', 4, 'Fasthand means immediately after landing the prior trick, switch or perform the next trick, in this case, switching to Penguin grip. While in Penguin grip, perform an Earn Turn.', 'https://youtu.be/zX1BiKn1i84?si=S2ZdwZYReWbTaQB1&t=24'),
('Swing Spike, Double Whirlwind', 4, 'Double Whirlwind is two Ken rotations.', 'https://youtu.be/zX1BiKn1i84?si=AKvY5p6AwGfMoF_3&t=40'),
('Handle Stall, 1-Turn Spike,', 4, 'Handle Stall position is the edge of the Base Cup', 'https://youtu.be/zX1BiKn1i84?si=-Us-yNIoctIgQAq9&t=50'),
('Scrambled 1-Turn Lighthouse, Tradespike', 4, 'In Tama Grip, pull the Ken toward oneself in a circular motion and release the Tama, then catch the Tama again and land in Lighthouse. Perform a Tradespike.', 'https://youtu.be/zX1BiKn1i84?si=C0srxBRmFTGDjSHL&t=59'),
('Lunar Flip, Flip In', 4, 'Land in Lunar first. Then flip the Ken so it lands back in Lunar. Then flip the Ken one rotation before the in.', 'https://youtu.be/zX1BiKn1i84?si=sLJAyUdLzTDZ26Na&t=69'),
('1-Turn Stuntplane Fasthand', 4, 'Pull the Ken up and make it rotate inward one rotation and Spike it with the Tama, and immediately grab the Ken after the Spike.', 'https://youtu.be/zX1BiKn1i84?si=Rb85szWC9vtDvzn6&t=78'),
('Stilt, Downspike', 4, 'In Tama grip, pull the Ken up so that the Ken lands with the spike down, and the top edge of the Big Cup now balances on the Tama bevel. Then Downspike.', 'https://youtu.be/zX1BiKn1i84?si=UD7K0gyoZyzVqYUe&t=91'),
('Sweets Special', 4, 'In Ken grip, swing the Tama under the left finger and over it so the string wraps it. Let the Tama continue and wrap around the top of the Spike and bottom of the Spike. Then land the Tama on the Big Cup. Let go of the Ken from the right hand and with the string wrapped around the left finger, the Ken and Tama can spin and rotate around the finger. Perform this rotation a few times, then grab the Ken with the right hand to Spike.', 'https://youtu.be/aUABcc3rJfc?si=j1qi8qmw1T6rzAEU&t=6'),
('Spacewalk, 1-Turn Airplane', 4, 'Spacewalk as normal, the Ken should perform one full rotation before the in.', 'https://youtu.be/aUABcc3rJfc?si=w_slJLUk8vAPSqoo&t=12'),
('Swing Spike, Double Whirlslinger', 4, 'The whirlslinger is performing an Earth turn and a Gunslinger, and the double means two rotations of Gunslinger.', 'https://youtu.be/aUABcc3rJfc?si=nmbGRMgYMrH7qAtO&t=30'),
('1-Turn Tap Reverse, 1-Turn Falling In', 4, 'Pull the Ken up so it rotates about a half of a rotation, but tap the Base Cup of the Ken with the Tama so it rotates back the opposite direction one full rotation before the in.', 'https://youtu.be/aUABcc3rJfc?si=xJYf6FdnB-3iWmes&t=44'),
('Bird, 1-Turn Over the Valley, 1-Turn Spike', 4, 'Over the Valley means switching the Tama to the Small Cup edge.', 'https://youtu.be/aUABcc3rJfc?si=-HwgV5HrD_9aiNZi&t=50'),
('Lunar, Tradespike', 4, 'While in Lunar, toss the Ken and Tama up and grab the Ken to Spike.', 'https://youtu.be/aUABcc3rJfc?si=ANJFtA-qpus9p-xq&t=59'),
('Lightning Drop Swap Spike', 4, 'In Ken Grip, swing and toss the Ken and Tama in a Spacewalk motion so that both rotate together about 1 and a half rotations, grabbing the Tama at the end of the rotations. Then swap the Tama for the Ken and Spike.', 'https://youtu.be/_tijff0FyfI?si=OiVulaxuxDiaiXJu&t=5'),
('2-Turn Airplane', 4, 'Pull and flip the Ken two full rotations from Tama grip for the in.', 'https://youtu.be/_tijff0FyfI?si=rzfNSjaaK_Z4j_yf&t=30'),
('Juggle Spike', 4, 'From Ken grip, perform a Juggle like normal, but Spike at the end of the Juggle.', 'https://youtu.be/_tijff0FyfI?si=X7MDRqVZBoGDysv2&t=74'),
('Flying V, 1-Turn Airplane', 4, 'Holding the Ken, swing the Tama around and let the string wrap around your index finger and the inner part of the big cup, as the tama comes around, switch the tama your primary hand. You will end up holding the tama in your primary hand, and the string wrapped once around your finger and the edge of the big cup. The Ken will rotate one rotation before the in.', 'https://youtu.be/_tijff0FyfI?si=kYgA6jTzr8CbY6Xi&t=86'),
('Candle Grip, Underbird, Spike', 4, 'Holding the Spike facing downwards, land in Underbird, the bottom edge of the Big Cup. Then flip the Ken to grab it in a normal grip and Spike.', 'https://youtu.be/_tijff0FyfI?si=DJIAhUXK9dZGgg0V&t=95'),
('Stilt, Tradespike', 4, 'In Tama grip, pull the Ken up so that the Ken lands with the spike down, and the top edge of the Big Cup now balances on the Tama bevel. Then toss the Ken and tama and grab the Ken to Spike.', 'https://youtu.be/_tijff0FyfI?si=5cI3ZZJSjn1QR98m&t=105'),
('Sara Grip Big Cup, Orbit Penguin Big Cup, Grip Change Spike', 4, 'First, land Big Cup in Sara Grip, toss the Tama up and Orbit the Tama, landing the Tama in a Penguin grip Big Cup, finally, toss the Ken and Tama up, switch to a normal grip for the Spike.', 'https://youtu.be/_tijff0FyfI?si=XKZkWAzyCPhLOm-o&t=118'),
('Lighthouse, Stuntplane', 4, 'Land Lighthouse, then grab the Tama to Spike the Ken with the Tama as in Stuntplane.', 'https://youtu.be/_tijff0FyfI?si=UXIt1Q2G8afbWIWc&t=136'),
('Downspike Fasthand, Jumping Stick', 4, 'Downspike, but immediately grab the Tama. Then perform a Jumping Stick.', 'https://youtu.be/HauDJtV4ZzQ?si=7m-9X_vAM-JjqwEb&t=13'),
('1-Turn Lighthouse, Penguin Spike', 4, 'Perform a one rotation Lighthouse like normal, when trading to Spike, grab the Ken in a Penguin grip.', 'https://youtu.be/HauDJtV4ZzQ?si=04mx51dHfl8rp4Pa&t=95'),
('Gunslinger Spike, Whirlslinger', 4, 'Place finger underneath Little Cup, rotate Ken around finger while also pulling Tama up to Spike it. The whirlslinger is performing an Earth turn and a Gunslinger', 'https://youtu.be/o2V8ncityq0?si=9qPSB4red3J6hSoO&t=41'),
('Hanging Ken Flip Spike', 4, 'In Hanging grip with the Tama next to the Sarado, pull both the Ken and Tama upward. Grab the Ken and perform a Ken flip before Spiking the Tama while the Tama is still in the air.', 'https://youtu.be/o2V8ncityq0?si=BTyTdLUKvmATAzdb&t=50'),
('Inward Lunar, Lunar, Flip In', 4, 'Inward Lunar is landing on the Big Cup on the Tama but the handle faces toward the body. Flip the Ken so it rotates a half of a rotation and land a Small Cup Lunar. Finally, perform a Flip In.', 'https://youtu.be/o2V8ncityq0?si=5ldM3LF551sy2PTi&t=71'),
('Big Cup, Shove-It Big Cup, Spike', 4, 'Shove-It is a horizontal Ken flip that rotates counter clockwise.', 'https://youtu.be/o2V8ncityq0?si=SlgY3zGxuCkroQMU&t=82'),
('Bird, Downspike', 4, 'Perform a Bird as usual. Toss the Ken to grab the Ken with the Spike facing downward and perform a Downspike.', 'https://youtu.be/o2V8ncityq0?si=GdAYW1MWzHuUJeH1&t=91'),
('2-Turn Lighthouse, Tradespike', 4, '2-Turn is two rotations', 'https://youtu.be/XLi2qPb-Hls?si=9-bmVtXuMPZylDya&t=63'),
('C-Whip, In', 4, 'While holding the Tama with fingers grabbing over the top of it, lift the Ken up, swing or whip the string slack in a downwards direction so it catches the and hooks the edge of the Big Cup. While in this position, toss the Ken up and in.', 'https://youtu.be/XLi2qPb-Hls?si=Fi_5zHKBd2LaeP0E&t=104'),
('Bird Over the Valley, Downspike', 4, 'Perform Bird as usual. Over the Valley is tossing the Tama up so that it lands on the other cup top edge. Lastly, toss the Ken and Tama together and switch grip so that the Spike faces downwards for a Downspike.', 'https://youtu.be/XLi2qPb-Hls?si=2aD9bnMJaMH2QcNS&t=124'),
('Stuntplane Fast Leg Catch', 4, 'Perform a Stuntplane like usual, but let go of both the Ken and Tama and catch them still Spiked between the legs or knees.', 'https://youtu.be/7sQGDd2zB0M?si=1b8SneoD2KoESInt&t=98'),
('2-Turn Airplane', 5, '2-Turn is two rotations before the in.', 'https://youtu.be/6b4oF0v_PHM?si=ycpzuQhUCoYnGHVD&t=5'),
('2-Turn Lighthouse', 5, '2-Turn is two rotations before landing in Lighthouse.', 'https://youtu.be/6b4oF0v_PHM?si=clBxjNhNrTVJBcjK&t=9'),
('Ken Flip, 1-Turn Lighthouse', 5, 'In Ken grip, pull up the Tama and Ken together, but flip the Ken one rotation, and land in Lighthouse. Then in.', 'https://youtu.be/6b4oF0v_PHM?si=yilzom4rndp-bcCL&t=43'),
('Airplane, Base Cup, Airplane In', 5, 'The Airplane In involves swapping to Tama grip to in.', 'https://youtu.be/scnTRzVTsjI?si=rjWvXPqPLwuKX3R6&t=5'),
('Swing Spike, Inward Whirlwind', 5, 'Inward Whirlwind is an Earth Turn and Ken flip, but the Ken rotates in the opposite direction.', 'https://youtu.be/scnTRzVTsjI?si=rXlPhKTN9qHw6uJz&t=11'),
('Inward Lunar, Tradespike', 5, 'Inward Lunar is landing on the Big Cup on the Tama but the handle faces toward the body. Then toss the Ken and Tama up and grab the Ken to Spike.', 'https://youtu.be/scnTRzVTsjI?si=cSFJ8FSJp-E2Plt4&t=53'),
('Penguin Base Cup, Double Flip Cup, Spike', 5, 'Double Flip Cup is two rotations and landing in a normal grip Base Cup.', 'https://youtu.be/scnTRzVTsjI?si=Ha3bkUNqRbOVCHLp&t=64'),
('Big Cup, Ken Flip Lighthouse, Falling In', 5, 'Ken Flip Lighthouse is a one rotation flip and Tama grip switch to Lighthouse', 'https://youtu.be/scnTRzVTsjI?si=Ol1ySuxILspKUlso&t=71'),
('Downspike, Airplane In', 5, 'Airplane In involves tossing the Ken up so it rotates once like a Jumping Stick and switching to Tama grip for the in.', 'https://youtu.be/scnTRzVTsjI?si=e3UXcrViffWaNBOh&t=81'),
('Spacewalk Handroll Flip Spike', 5, 'Spacewalk and catch like normal, but then let the string wrap around the hand and have the Ken and Tama roll and spin around the entire hand at least one rotation, at the end, grab the Ken, perform a Ken Flip and Spike.', 'https://youtu.be/Tfoq1UYbWME?si=dc0F1AnvdZszqmeo&t=5'),
('Big Cup, Ken Flip Lighthouse, Downspike', 5, 'Ken Flip Lighthouse is a one rotation flip and Tama grip switch to Lighthouse. Toss both the Ken and Tama up and grab the Ken with the Spike facing downward to Downspike.', 'https://youtu.be/Tfoq1UYbWME?si=GqAXf21Y-wGt8g-I&t=15'),
('Flip Penguin Base Cup, Flip Base Cup, Spike', 5, 'Ken grip, pull the tama up and also perform a Ken Flip and land in base cup in a Penguin grip, then perform a Ken flip to a normal grip Base Cup, then Spike.', 'https://youtu.be/Tfoq1UYbWME?si=85g-KsIK8TU26k1W&t=48'),
('Boarders Balance, Lighthouse, Falling In', 5, 'Boarder Balance is balancing the tip of the Spike on the Tama. For Lighthouse, flip the Ken half a rotation into Lighthouse. Then Spike.', 'https://youtu.be/Tfoq1UYbWME?si=SAOZknbQU19VtCgP&t=63'),
('Mooncircle Swing Gunslinger Spike', 5, 'In Ken grip, toss the Ken and Tama in a circular motion one entire rotation in the air together and catch the Ken and perform a Gunslinger before the Spike.', 'https://youtu.be/Tfoq1UYbWME?si=OYFq9kj4oZatD2ol&t=74'),
('Ken Flip Downspike', 5, 'Pull up Ken Flip one rotation and Downspike', 'https://youtu.be/Tfoq1UYbWME?si=nlsTfqzJw0lvilN3&t=87'),
('Airplane, 1.5-Turn Tap Reverse, 1-Turn Jumping Stick', 5, 'The 1.5 Turn Tap Reverse is flipping the Ken out of the Tama and letting it rotate one and a half rotations and then tapping the Base Cup edge with the Tama so it rotates the other direction one full rotation into an in.', 'https://youtu.be/ohKY5XttlsA?si=6ye6c9Y5x41P8ICP&t=6'),
('Double Juggle Spike', 5, 'Perform one extra Juggle before Spike.', 'https://youtu.be/ohKY5XttlsA?si=dymq3-27AIn4DS2f&t=18'),
('Around Gunslinger', 5, 'Perform a Gunslinger landing in each position before ultimately performing a Spike. Big Cup, Little Cup, Base Cup.', 'https://youtu.be/ohKY5XttlsA?si=4zrX_BiLbZFr35AV&t=29'),
('Mooncircle Swap 1-Turn Airplane', 5, 'Perform a full Mooncircle (In Ken grip, toss the Ken and Tama in a circular motion one entire rotation in the air together and catch the Ken again), toss the Ken so it rotates one and a half rotations, grabbing the Tama for the in.', 'https://youtu.be/ohKY5XttlsA?si=RnIWE2JfqGvoA07_&t=51'),
('1-Turn Tap Reverse, 1.5-Turn Swap Spike', 5, 'Pull the Ken up so it rotates one full rotation and tap it with the edge of the Base Cup, the Ken will rotate one and a half rotations, toss the Tama and grab the Ken for the Spike.', 'https://youtu.be/ohKY5XttlsA?si=zvGX0a8qqeS44YN8&t=64'),
('Underbird, Axe, Falling In', 5, 'Underbird is pulling the Tama up and landing the Tama bevel on the bottom edge of the Big Cup. The Spike will be facing downwards. Toss both the Tama and Ken together and grab the Tama. Axe is the Ken above the Tama with the bottom edge of the Big Cup touching the bevel of the Tama. Toss the Ken up to in.', 'https://youtu.be/ohKY5XttlsA?si=_sCWUg9dROe6XCHl&t=70'),
('Ken Flip Reverse, Ken Flip Lighthouse, Falling In', 5, 'Perform a Ken Flip, then a Reverse Ken Flip and switch to Tama grip to land in Lighthouse. Then in.', 'https://youtu.be/ohKY5XttlsA?si=htFICX-Uz-reb95Y&t=80'),
('Lunar Barrel Roll, Falling In', 5, 'Land in Lunar position. Flip the Ken so that it rotates around the plane of the Handle and lands back in Lunar position. Then in.', 'https://youtu.be/ohKY5XttlsA?si=6HpyKMsySpmKLrBt&t=94'),
('Boarders Balance, Tradespike', 5, 'Boarder Balance is balancing the tip of the Spike on the Tama. Then Tradespike.', 'https://youtu.be/ohKY5XttlsA?si=jMrVHNAlkON9jawN&t=105'),
('2-Turn Swing U.F.O., Swap Spike', 5, 'In Tama grip, pull the Ken so that it rotates two rotations horizontally and while the Ken is rotating, swap and grab the Ken in a Penguin grip to Spike.', 'https://youtu.be/ohKY5XttlsA?si=6IRsWgc0qwKNaXWb&t=114'),
('Swap Airplane, 0.5 Swap Spike', 5, 'In Ken grip, pull the Tama up, and toss the Ken so it flips half a rotation and and grab the Tama to in. Flip the Ken out half a rotation, toss the Tama up, grab the Ken and then Spike.', 'https://youtu.be/qUCb3_z5fb4?si=hlFZqZpnHn5A_374&t=19'),
('Knee Bounce, 1-Turn Stuntplane', 5, 'In Tama grip, pull the Ken up and bounce the Base Cup off the knee so it flips one inward rotation and then Stuntplane', 'https://youtu.be/qUCb3_z5fb4?si=A-rIDyhyCLuBewbH&t=28'),
('Swing Spike, Candle, Spike', 5, 'For Candle, toss the Ken and Tama upwards, but the Ken rotates half a rotation, grabbing the Spike as in Candle grip. Then flip the Ken half a rotation to Spike.', 'https://youtu.be/qUCb3_z5fb4?si=-iHyn7V6toa0mWcW&t=61'),
('Base Cup Hanging Stuntplane Fasthand', 5, 'Hanging Spike position, but the bottom of the ken is on the tama. Toss the Kendama up and perform a Stuntplane and immediately grab the Ken.', 'https://youtu.be/qUCb3_z5fb4?si=Zt5bFs0Gq6rcxoPF&t=71'),
('Scramble 1-Turn Lunar, Flip In', 5, 'Swing the Ken like a normal Airplane, as the Ken comes around, release and flip the tama in your hand, let the Ken swing around one more time and also turn one rotation before landing in Lunar.', 'https://youtu.be/qUCb3_z5fb4?si=5RknNllO5YL1dryV&t=83'),
('Handle Stall, Falling In', 5, 'Handle Stall position is the edge of the Base Cup. For the Falling In, toss the Ken up and grab the Tama and let the Ken fall in.', 'https://youtu.be/qUCb3_z5fb4?si=fUPpd5qDeG97LTAc&t=92'),
('Base Cup, Flip Base Cup, Flip Downspike', 5, 'Base Cup as normal. Perform a Base Cup flip. Then toss the Ken and Tama up together and perform a Ken Flip before grabbing the Ken and Downspike.', 'https://youtu.be/qUCb3_z5fb4?si=ayURwAsbZJLOiEjp&t=100'),
('Swirl to Swap Spike', 5, 'Let the string wrap around the finger, release the Ken and let the Ken and Tama spin around the finger at least once, grab the Tama and then toss and grab the Ken and Spike.', 'https://youtu.be/ffDt-DQ7x10?si=nCExefvDvJ5nE9gH&t=5'),
('Triple Jumping Stick', 5, 'Airplane as normal. Triple Jumping Stick is three rotations.', 'https://youtu.be/ffDt-DQ7x10?si=8b6svNsLAyWV2C3N&t=20'),
('Around Denmark', 5, 'Big Cup, Ken Flip to Little Cup, toss the Ken and Tama together and grab the Tama to in, toss the Ken out grabbing it and land in Base Cup, then Downspike', 'https://youtu.be/ffDt-DQ7x10?si=hzeF5v7lY_KqMtYE&t=33'),
('Base Cup, Ken Flip Base Cup, Ken Flip Lighthouse, Tradespike', 5, 'Base Cup as normal, then perform a Ken Flip to Base Cup, then Ken Flip and grab the Tama to land in Lighthouse, then Tradespike.', 'https://youtu.be/ffDt-DQ7x10?si=KwQAqataPrnNtwpK&t=48'),
('Juggle Kick Big Cup, Spike, Earth Turn', 5, 'Juggle like normal and before landing the Tama, kick it with the side of the foot so the Tama goes upward and land onto the Big Cup', 'https://youtu.be/ffDt-DQ7x10?si=LZGLWtnEkznf1Cwl&t=73'),
('Ghost Lighthouse, Insta Lighthouse Flip, Tradespike', 5, 'In Ken grip, pull the Tama up, then let go of the Ken and grab the Tama, and land a Lighthouse, but immediately perform a Lighthouse Flip. Tradespike to in.', 'https://youtu.be/ffDt-DQ7x10?si=D0lt3PUaUYp4LRUr&t=91'),
('Underbird, Nod Off Underbird, Falling In', 5, 'Pull the Tama up and land the Tama bevel on the bottom edge of the Big Cup. The Spike will be facing downwards. Nod Off is rolling the Tama onto the Big Cup then returning it back to Underbird position. For the in, toss both the Tama and Ken in the air and grab the Tama for the in.', 'https://youtu.be/ffDt-DQ7x10?si=FLU3UM8k-sFXxQZS&t=111'),
('Inward Lunar Flip, Falling In', 5, 'First perform an Inward Lunar. Inward Lunar is landing on the Big Cup on the Tama but the handle faces toward the body. Perform a flip so that the Ken lands back in Inward Lunar Flip position. Then toss the Ken up and in.', 'https://youtu.be/ffDt-DQ7x10?si=T0OTVdtY1tk6CK3Z&t=121'),
('Swivel Downspike Fasthand, Swivel Spike', 5, 'Holding the Big and Little Cups between the fingers, pull the Tama up, then swivel or rotate the Ken so the Spike faces downwards and perform a Downspike. Then toss both the Ken and Tama up in the air and grab the Big and Little Cups between the fingers, swivel or rotate the Ken so the Spike faces upwards and Spike.', 'https://youtu.be/ffDt-DQ7x10?si=_SGWM1pnn8q1rciW&t=134'),
('Candle Grip Kenflip, Downspike', 5, 'Candle grip, pull the Tama up, flip the Ken so it rotates one rotation, and grab the Ken while the spike is facing downward, and then Downspike.', 'https://youtu.be/ffDt-DQ7x10?si=P9gMie03SgRS2w72&t=158'),
('2-Turn Airplane, Double Jumping Stick', 5, '2-Turn is two rotations of the Ken before the Airplane in. Double Jumping Stick is two rotations of the Ken.', 'https://youtu.be/HB-RCiZ5Ndk?si=w1R2bJksmryfKlBy&t=18'),
('Tap Juggle Spike', 5, 'Pull the Ken up so it rotates half a rotation and tap it with the edge of the Base Cup, then perform a Juggle (toss the Tama, Ken, Tama) and Spike.', 'https://youtu.be/HB-RCiZ5Ndk?si=LrdsA-wbZRD-BPy0&t=46'),
('Ken Flip Tap Lighthouse, Tradespike', 5, 'Pull the Tama up and Ken Flip and then grab the Tama and tap the edge of the Base Cup of the Ken with the Tama and land in Lighthouse. Then Tradespike.', 'https://youtu.be/HB-RCiZ5Ndk?si=wU1I3rdGWZ19o9fE&t=59'),
('Mooncircle Fast Swing Spike', 5, 'Perform a Mooncircle (In Ken grip, toss the Ken and Tama in a circular motion one entire rotation in the air together and catch the Ken again) and immediately Spike without any extra rotations.', 'https://youtu.be/HB-RCiZ5Ndk?si=i_2foA-_2rmmvfbW&t=77'),
('Ghost Lunar, Stuntplane Fasthand', 5, 'In Ken grip, pull the Tama up, and lightly toss the Ken onto the Tama so it lands in Lunar. Then toss the Ken up and Stuntplane.', 'https://youtu.be/HB-RCiZ5Ndk?si=cgl3nZG_7pdvvm0r&t=94'),
('Stuntplane Fast Under the Leg Catch (both feet on the ground)', 5, 'Perform a Stuntplane like normal and immediately after landing it, let it fall and grab the Ken with the Tama Spiked.', 'https://youtu.be/HB-RCiZ5Ndk?si=-QMXJK81fbEC-fdV&t=103'),
('Double Lighthouse Flip, Inward Double Lighthouse Flip, In', 5, 'Land in Lighthouse first. Then flip the Ken so it rotates two rotations. Then flip the Ken so it flips the opposite direction two rotations.', 'https://youtu.be/Pi-uS_u4G1s?si=pswgz-cYlOztFO31&t=72'),
('Bird, Nod Off On Over the Valley, Nod Off On, 1-Turn Spike', 5, 'Land in Bird like normal, then roll the Tama onto the Big Cup and back into Bird, then toss the Tama over to the Little Cup edge, roll the Tama onto the Little Cup and then back onto Little Bird, then flip the Tama so it rotates one rotation into a Spike', 'https://youtu.be/Pi-uS_u4G1s?si=5fCFHxl4o1gNnCbl&t=83'),
('Inward Lunar, Flip Cushion Tap Inward Lunar, In', 5, 'Inward Lunar is landing on the Big Cup on the Tama but the handle faces toward the body. Perform an Inward Lunar Flip and let it overrotate slightly, tapping the bottom of the Base Cup edge and then landing into Inward Lunar Flip. Then in.', 'https://youtu.be/Pi-uS_u4G1s?si=2LtRpgIe2tMtArMh&t=97'),
('Snake Bite, In', 5, 'In Tama grip, whip the bead or weight that is in the inside of the Tama out so that it hooks around the Big Cup. Then pull up the Ken and in.', 'https://youtu.be/Pi-uS_u4G1s?si=lDTUNC0RufFfylwR&t=111'),
('Downspike, Down Earth Fasthand', 5, 'Downspike as usual. Perform a Down Earth and immediately switch to the Tama.', 'https://youtu.be/Pi-uS_u4G1s?si=CS8bCk7uyT37b76S&t=118'),
('Bird Over the Valley, Handle Stall, 1-Turn Spike', 5, 'Bird. Then toss the Tama over to Little Bird (top edge of the small cup). Then toss the Tama so it lands on the Base Cup edge.', 'https://youtu.be/9PsVzyDopc8?si=eX2-aJb8jt-KXG5q&t=73'),
('Stilt, Stilt Flip, Downspike', 5, 'In Tama grip, pull the Ken up so that the Ken lands with the spike down, and the top edge of the Big Cup now balances on the Tama bevel. Then flip the Ken so it flips one rotation and lands back into Stilt. Then swap and Downspike.', 'https://youtu.be/9PsVzyDopc8?si=ioWkeiBafG9uJy3l&t=109'),
('Boarders Balance, Flip In', 5, 'Boarder Balance is balancing the tip of the Spike on the Tama. Flip the Ken in.', 'https://youtu.be/9PsVzyDopc8?si=NgCjGt-z44GdaM_m&t=120'),
('Candle, Juggle Candle, Spike', 5, 'Candle grip, Juggle (toss Tama, Ken, Tama), but grab the Spike as in Candle grip. Then flip the Ken half a rotation to Spike.', 'https://youtu.be/9PsVzyDopc8?si=uWwg2o9RBn323p0h&t=129'),
('Lightning Drop 1-Turn Lighthouse, Downspike', 5, 'In Ken Grip, swing and toss the Ken and Tama in a Spacewalk motion so that both rotate together about 1 and a half rotations, grabbing the Tama at the end of the rotations, the Ken will also rotate one full rotation into a Lighthouse. Then Downspike.', 'https://youtu.be/9PsVzyDopc8?si=OqAj0B9Y8h5Dfrpw&t=158'),
('Airplane, 1.5 Swap Juggle Spike', 5, 'After Airplane, toss the Ken so it rotates one and a half rotations then perform a Juggle (toss the Tama, Ken, Tama) then grab Ken and Spike.', 'https://youtu.be/-9VBK34xwSU?si=_AmDfb84YqmhH1hS&t=38'),
('1-Turn Lighthouse, Insta Stuntplane Fasthand', 5, 'Perform 1-Turn Lighthouse as usual, but immediately after landing it, perform a Stuntplane and then immediately switch to Ken grip.', 'https://youtu.be/-9VBK34xwSU?si=kCNiB6ScMPz_1Asg&t=47'),
('Stilt Flip, Flip In', 5, 'In Tama grip, pull the Ken up so that the Ken lands with the spike down, and the top edge of the Big Cup now balances on the Tama bevel. Flip the Ken so it lands back into Stilt. Then flip in.', 'https://youtu.be/-9VBK34xwSU?si=ouzLrYVllJKaWqut&t=60'),
('Backward Inward Lunar, Lunar, Flip In', 5, 'Release the Ken and let it swing and begin to land as if it was a normal Lunar, but have the Ken turn and land in Inward Lunar. Flip the Ken so it rotates half a rotation onto Lunar with Little Cup. Then flip in.', 'https://youtu.be/-9VBK34xwSU?si=WMmBJrMbJaPcu0tN&t=71'),
('Clap Around Japan', 5, 'In Ken Grip and between each position, clap hands together. Big Cup, Little Cup, Spike.', 'https://youtu.be/-9VBK34xwSU?si=_iWLsKXFpC-Fiz7r&t=84'),
('Ken Flip Flip Spike', 5, 'Pull the Tama up and Ken Flip and then Ken Flip a second time and Spike the Tama while it is in the air.', 'https://youtu.be/-9VBK34xwSU?si=9IevSNNjOgNF2sG_&t=94')